import csv
from pathlib import Path

# This script deterministically assigns a stock_status (あり/残りわずか/なし)
# using product fields (name, review_number, score). This is generated by ChatGPT.

BASE_DIR = Path(__file__).resolve().parents[1]
CSV_PATH = BASE_DIR / "data" / "products.csv"
BACKUP_PATH = BASE_DIR / "data" / "products.csv.bak"

def compute_stock_status(name: str, review_number: int, score: float) -> str:
    # deterministic pseudo-AI scoring using product attributes
    name_hash = sum(ord(c) for c in name)
    pseudo_rand = name_hash % 100
    demand = review_number * 0.6 + score * 10 + pseudo_rand * 0.1
    if demand >= 250:
        return "あり"
    if demand >= 150:
        return "残りわずか"
    return "なし"


def main():
    if not CSV_PATH.exists():
        print(f"CSV not found: {CSV_PATH}")
        return
    # backup
    CSV_PATH.replace(BACKUP_PATH)
    # read backup and produce updated CSV
    with BACKUP_PATH.open(encoding="utf-8") as f:
        reader = csv.DictReader(f)
        rows = list(reader)
        fieldnames = reader.fieldnames or []

    if "stock_status" not in fieldnames:
        fieldnames.append("stock_status")

    for r in rows:
        try:
            review_number = int(r.get("review_number", "0"))
        except ValueError:
            review_number = 0
        try:
            score = float(r.get("score", "0"))
        except ValueError:
            score = 0.0
        name = r.get("name", "")
        r["stock_status"] = compute_stock_status(name, review_number, score)

    with CSV_PATH.open("w", encoding="utf-8", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)

    # print summary
    from collections import Counter
    c = Counter(r["stock_status"] for r in rows)
    print("Updated:", CSV_PATH)
    print("Counts:")
    for k, v in c.items():
        print(k, v)

if __name__ == "__main__":
    main()
